name: Build Java JAR

on: [push, pull_request, workflow_dispatch]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build_jni:
    name: jni on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            outdir: linux_64
          - os: windows-latest
            outdir: windows_64
          - os: macos-latest
            outdir: osx_64
    steps:
      - uses: actions/checkout@v3

      - name: Install rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          # stable doesn't have --out-dir
          toolchain: nightly
          override: true

      - name: Build
        working-directory: ./jni
        # TODO: 32bit vs 64bit?
        # https://github.com/scijava/native-lib-loader
        run: cargo build --release -Z unstable-options --out-dir ../build/natives/${{ matrix.outdir }}/

      - uses: actions/upload-artifact@v3
        with:
          name: natives
          path: ./build/natives/*

  build_java:
    name: java
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    needs: [build_jni]

    steps:
      - uses: actions/checkout@v3

      - name: Load outputs
        uses: actions/download-artifact@v3
        with:
          name: natives
          path: natives

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'microsoft'
          architecture: x64
          cache: maven

      - name: Build with Maven
        working-directory: ./java
        run: mvn --batch-mode package failsafe:integration-test

      - uses: actions/upload-artifact@v3
        with:
          name: java
          path: ./java/target/*.jar

      # TODO: publish to maven (only from ubuntu)

